version: "3.6"
services:
  bot:
    image: node:14.18.1
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - flavorsbsc
    command: npm run start

  mongo:
    image: mongo
    restart: always
    networks:
      - flavorsbsc
    environment:
      MONGO_INITDB_ROOT_USERNAME: flavorsbsc
      MONGO_INITDB_ROOT_PASSWORD: flavorstoken

  db-ui:
    image: mongo-express
    restart: always
    networks:
      - flavorsbsc
    ports:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: flavorsbsc
      ME_CONFIG_MONGODB_ADMINPASSWORD: flavorstoken
      ME_CONFIG_MONGODB_URL: mongodb://flavorsbsc:flavorstoken@mongo:27017/

networks:
  flavorsbsc:
