version: "3.6"
services:
  bot:
    image: node:14.18.1
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - flavorsbsc
    command: npm run start

  mongo:
    image: mongo
    restart: always
    networks:
      - flavorsbsc
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"

  db-ui:
    image: mongo-express
    restart: always
    networks:
      - flavorsbsc
    ports:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_DB_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_DB_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongo:27017/"

networks:
  flavorsbsc:
